<<<<<<< HEAD
FROM amos6224/git 

 MAINTAINER Jeff

 RUN apt-get update
 RUN apt-get install -y wget gcc make g++ build-essential ca-certificates mercurial git bzr libsqlite3-dev sqlite3

 RUN wget https://go.googlecode.com/files/go1.2.src.tar.gz && tar zxvf go1.2.src.tar.gz && cd go/src && ./make.bash 

 ENV PATH $PATH:/go/bin:/gocode/bin
 ENV GOPATH /gocode

 RUN mkdir -p /gocode/src/github.com/drone

 ADD . /gocode/src/github.com/drone/drone

 WORKDIR /gocode/src/github.com/drone/drone

 RUN make deps
 RUN make
 RUN make install

 EXPOSE 80

 ENTRYPOINT ["/usr/local/bin/droned"]

 CMD ["--port=:80", "--path=/var/lib/drone/drone.sqlite"]
=======
image: go1.2
env:
  - GOROOT=/usr/local/go
  - GOPATH=$PWD/Godeps/_workspace:/var/cache/drone
  - PATH=$PWD/Godeps/_workspace/bin:/var/cache/drone/bin:$PATH
script:
  - sudo apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null
  - sudo apt-get -y install htop
>>>>>>> 067a69ba6cb51048cdaa963e63b910d79998dfeb
