image: amos6224/git
script:
 touch teste.txt
notify:
  email:
    recipients:
      - jeff@namely.com
      - attila@namely.com

  hipchat:
    room: CI
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true
